name: Build Podinfo image

env:
  DOCKER_SERVER: ghcr.io
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches-ignore:
      - production
      - staging
    paths:
      - src/wrk2

jobs:
  build:
    name: Build Docker Images
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Log into GitHub registry
        run: echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_SERVER}" --username "${DOCKER_USER}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          cd docker/wrk2
          ./build-push-docker.sh
