name: Build Terraform AzureCli image

env:
  DOCKER_SERVER: ghcr.io
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches-ignore:
      - production
      - staging
    paths:
      - docker/terraform/Dockerfile

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log into GitHub registry
        run: echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_SERVER}" --username "${DOCKER_USER}" --password-stdin

      - name: Build and Push Docker Image
        run: ./build-terraform-image.sh
