name: Build Podinfo image

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches-ignore:
      - production
      - staging
    paths:
      - src/podinfo

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build and Push Docker Image
        run: ./build-podinfo-image.sh "${DOCKER_PASSWORD}"
