name: Build Terraform AzureCli image

env:
  DOCKER_SERVER: ghcr.io
  DOCKER_USER: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches-ignore:
      - production
      - staging
    paths:
      - docker/terraform/Dockerfile

jobs:
  build:
    name: Build Docker Images
    # runs-on: ubuntu-20.04
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log into GitHub registry
        run: echo "${DOCKER_PASSWORD}" | docker login "${DOCKER_SERVER}" --username "${DOCKER_USER}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="terraform-azure-cli"
          DOCKER_FILE="$(pwd)/docker/terraform/Dockerfile"
          TERRAFORM_VERSION="$(grep -e '^ARG TERRAFORM_VERSION' ${DOCKER_FILE} | cut -d "=" -f 2)"
          DOCKER_TAG="${DOCKER_SERVER}/${DOCKER_USER}/${IMAGE_NAME}"

          docker build --tag="${DOCKER_TAG}:${TERRAFORM_VERSION}" --file="${DOCKER_FILE}" .

          docker tag "${DOCKER_TAG}:${TERRAFORM_VERSION}" "${DOCKER_TAG}:latest"

          docker push "${DOCKER_TAG}:${TERRAFORM_VERSION}"
          docker push "${DOCKER_TAG}:latest"
