name: Build Terraform AzureCli image

env:
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

on:
  push:
    branches-ignore:
      - production
      - staging
    paths:
      - docker/terraform/Dockerfile

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        run: ./build-terraform-image.sh "${DOCKER_PASSWORD}"
