name: Deploy Development Environment

on:
  push:
    branches:
      - development
    paths:
      - "**/*.tf"
      - "deploy-ingress.sh"
      - "deploy-external-dns.sh"

jobs:
  applyTerraform:
    name: Deploy AKS Cluster
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/kborovik/terraform-azure-cli:0.13.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Apply Terraform Scripts
        run: |
          cd terraform
          ./apply-terraform.sh DEV ${{ secrets.ARM_CLIENT_SECRET }} ${{ secrets.ARM_CLIENT_ID }} ${{ secrets.ARM_SUBSCRIPTION_ID }} ${{ secrets.ARM_TENANT_ID }}

      - name: Deploy Ingress Controller
        run: |
          ./deploy-ingress.sh DEV ${{ secrets.ARM_CLIENT_SECRET }} ${{ secrets.ARM_CLIENT_ID }} ${{ secrets.ARM_SUBSCRIPTION_ID }} ${{ secrets.ARM_TENANT_ID }}

      - name: Deploy External DNS
        run: |
          ./deploy-external-dns.sh DEV ${{ secrets.ARM_CLIENT_SECRET }} ${{ secrets.ARM_CLIENT_ID }} ${{ secrets.ARM_SUBSCRIPTION_ID }} ${{ secrets.ARM_TENANT_ID }}
